#version: '3.8'
services:
  app:
    image: laravel_8.2
    container_name: laravel_jwt
    ports:
      - "8082:80"
    volumes:
      - $PWD:/var/www/html
    # depends_on:
    #   - db

  # db:
  #   image: mysql:8.0
  #   container_name: laravel_db
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: secret
  #   volumes:
  #     - dbdata:/var/lib/mysql

# volumes:
#   dbdata:

